name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Autograding Marks
        uses: education/autograding-command-grader@v1
        with:
          test-name: Filter Algorithm Tests
          setup-command: npm install
          command: npm test
          timeout: 1
          max-score: 100

      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        if: always()
        with:
          runners: Filter Algorithm Tests
